Repository DeveloperAcademy-POSTECH/MC3-Team5-KnockKnock, pull requests merged in 2022-08, with the labels that each got.

#78 [FIX] 앨범 사진 로딩 시 렉이 발생하는 문제 수정
  KnockKnock/CoreData/CoreDataManager.swift
  KnockKnock/CoreData/KnockKnock.xcdatamodeld/KnockKnock.xcdatamodel/contents
  KnockKnock/KnockKnock/Album/MainAlbumViewController.swift
  KnockKnock/KnockKnock/Frame/FrameViewController.swift
  KnockKnock/KnockKnock/Frame/MainFrameViewController.swift
Labels: bug, enhancement, 🕸 마이즈

#80 [FEAT] 앨범, 액자에서 이미지 확대 기능 개편
  KnockKnock/KnockKnock.xcodeproj/project.pbxproj
  KnockKnock/KnockKnock/Album/CellDetailViewController.swift
  KnockKnock/KnockKnock/Frame/MainFrameViewController.swift
Labels: enhancement, 💄 UI, 💧오션

#82 [DOCS] Readme 파일 작성
  README.md
Labels: documentation, 🕸 마이즈

#84 [REFACTOR] RoomView에서 중복 사용되는 ImageView 코드 함수로 정리
  KnockKnock/KnockKnock/Album/CellDetailViewController.swift
  KnockKnock/KnockKnock/Album/MainAlbumViewController.swift
  KnockKnock/KnockKnock/DoorViewController.swift
  KnockKnock/KnockKnock/Frame/FrameViewController.swift
  KnockKnock/KnockKnock/Frame/MainFrameViewController.swift
  KnockKnock/KnockKnock/Letter/MainLetterViewController.swift
  KnockKnock/KnockKnock/Passcode/PasscodeViewController.swift
  KnockKnock/KnockKnock/PasscodeSetting/KeychainManager.swift
  KnockKnock/KnockKnock/PasscodeSetting/SettingViewController.swift
  KnockKnock/KnockKnock/RoomViewController.swift
Labels: 🕸 마이즈, 🛠 refactor

#85 [FEAT] 영어 / 한국어 Localization
  KnockKnock/KnockKnock.xcodeproj/project.pbxproj
  KnockKnock/KnockKnock/Album/CellDetailViewController.swift
  KnockKnock/KnockKnock/Album/MainAlbumViewController.swift
  KnockKnock/KnockKnock/Assets.xcassets/AppIcon.appiconset/Contents.json
  KnockKnock/KnockKnock/DoorViewController.swift
  KnockKnock/KnockKnock/Frame/FrameViewController.swift
  KnockKnock/KnockKnock/Frame/MainFrameViewController.swift
  KnockKnock/KnockKnock/Info.plist
  KnockKnock/KnockKnock/Letter/MainLetterViewController.swift
  KnockKnock/KnockKnock/Memo/MainMemoView.swift
  KnockKnock/KnockKnock/Memo/MemoDetailViewController.swift
  KnockKnock/KnockKnock/OnboardingView.swift
  KnockKnock/KnockKnock/Passcode/PasscodeViewController.swift
  KnockKnock/KnockKnock/PasscodeSetting/SettingViewController.swift
  KnockKnock/KnockKnock/RoomViewController.swift
  KnockKnock/Localizable/en.lproj/Localizable.strings
  KnockKnock/Localizable/ko.lproj/Localizable.strings
Labels: enhancement, 🕸 마이즈

#86 [MERGE] develop (~2022.08.10) -> main
  KnockKnock/KnockKnock.xcodeproj/project.pbxproj
  KnockKnock/KnockKnock/Album/CellDetailViewController.swift
  KnockKnock/KnockKnock/Album/MainAlbumViewController.swift
  KnockKnock/KnockKnock/Assets.xcassets/AppIcon.appiconset/Contents.json
  KnockKnock/KnockKnock/DoorViewController.swift
  KnockKnock/KnockKnock/Frame/FrameViewController.swift
  KnockKnock/KnockKnock/Frame/MainFrameViewController.swift
  KnockKnock/KnockKnock/Info.plist
  KnockKnock/KnockKnock/Letter/MainLetterViewController.swift
  KnockKnock/KnockKnock/Memo/MainMemoView.swift
  KnockKnock/KnockKnock/Memo/MemoDetailViewController.swift
  KnockKnock/KnockKnock/OnboardingView.swift
  KnockKnock/KnockKnock/Passcode/PasscodeViewController.swift
  KnockKnock/KnockKnock/PasscodeSetting/KeychainManager.swift
  KnockKnock/KnockKnock/PasscodeSetting/SettingViewController.swift
  KnockKnock/KnockKnock/RoomViewController.swift
  KnockKnock/Localizable/en.lproj/Localizable.strings
  KnockKnock/Localizable/ko.lproj/Localizable.strings
  Privacy.md
  README.md
Labels: enhancement
