Repository DeveloperAcademy-POSTECH/MC3-Team5-KnockKnock, pull requests merged in 2022-07, with the labels that each got.

#7 [FEAT] update memo
  KnockKnock/CoreData/CoreDataManager.swift
  KnockKnock/KnockKnock.xcodeproj/project.pbxproj
  KnockKnock/KnockKnock/Memo/MainMemoView.swift
  KnockKnock/KnockKnock/Memo/MemoDetailViewController.swift
Labels: enhancement

#44 [FEAT] 액자 기본 이미지 추가 / 액자 이미지 깨짐 수정
  KnockKnock/KnockKnock/Album/AlbumCollectionViewCell.swift
  KnockKnock/KnockKnock/Album/MainAlbumViewController.swift
  KnockKnock/KnockKnock/Frame/FrameCollectionViewCell.swift
  KnockKnock/KnockKnock/Frame/FrameViewController.swift
  KnockKnock/KnockKnock/Frame/MainFrameViewController.swift
  KnockKnock/KnockKnock/RoomViewController.swift
Labels: enhancement, 💄 UI, 🕸 마이즈

#45 [FEAT] 액자 사진 크롭 기능
  KnockKnock/KnockKnock.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  KnockKnock/KnockKnock/Frame/FrameViewController.swift
Labels: enhancement, 💧오션

#47 [FEAT] doorViewController 1번 탭할 시 토스트 알림 추가
  KnockKnock/KnockKnock/Assets.xcassets/frame person.imageset/Contents.json
  KnockKnock/KnockKnock/Assets.xcassets/frame person.imageset/frame person.svg
  KnockKnock/KnockKnock/DoorViewController.swift
  KnockKnock/KnockKnock/Frame/MainFrameViewController.swift
  KnockKnock/KnockKnock/RoomViewController.swift
Labels: 💄 UI, 💧오션, 🕸 마이즈

#48 [DESIGN] Navigation,main page detail
  KnockKnock/KnockKnock/AppDelegate.swift
  KnockKnock/KnockKnock/Assets.xcassets/navigationColor.colorset/Contents.json
  KnockKnock/KnockKnock/Assets.xcassets/roomImage.imageset/Contents.json
  KnockKnock/KnockKnock/Assets.xcassets/roomImage.imageset/ backimg-none2.pdf
  KnockKnock/KnockKnock/Assets.xcassets/roomImage.imageset/ backimg-none3.pdf
  KnockKnock/KnockKnock/Letter/MainLetterViewController.swift
  KnockKnock/KnockKnock/Memo/MainMemoView.swift
  KnockKnock/KnockKnock/Memo/MemoDetailViewController.swift
  KnockKnock/KnockKnock/Passcode/PasscodeViewController.swift
  KnockKnock/KnockKnock/RoomViewController.swift
Labels: 💄 UI, 🐯창브로

#51 [DESIGN] RoomView UI 위치 수정
  KnockKnock/KnockKnock/Assets.xcassets/drawer.imageset/Contents.json
  KnockKnock/KnockKnock/Assets.xcassets/drawer.imageset/Drawer2.svg
  KnockKnock/KnockKnock/Letter/MainLetterViewController.swift
  KnockKnock/KnockKnock/RoomViewController.swift
Labels: 💄 UI, 🐯창브로

#52 [FEAT] 비밀번호 변경기능 추가
  KnockKnock/KnockKnock/DoorViewController.swift
  KnockKnock/KnockKnock/Passcode/PasscodeViewController.swift
  KnockKnock/KnockKnock/PasscodeSetting/SettingViewController.swift
Labels: enhancement, 🐶 저니

#55 [FEAT] Background music 추가
  KnockKnock/Audio/AudioManager.swift
  KnockKnock/Audio/Music/forest.mp3
  KnockKnock/KnockKnock.xcodeproj/project.pbxproj
  KnockKnock/KnockKnock/Assets.xcassets/musicnote-x.imageset/Contents.json
  KnockKnock/KnockKnock/Assets.xcassets/musicnote-x.imageset/musicnote-x.png
  KnockKnock/KnockKnock/Assets.xcassets/musicnote2.imageset/Contents.json
  KnockKnock/KnockKnock/Assets.xcassets/musicnote2.imageset/musicnote2.png
  KnockKnock/KnockKnock/RoomViewController.swift
Labels: 💄 UI, 🤦‍♂️제리

#57 [REFACTOR] showToast 함수 중복 코드 정리
  KnockKnock/KnockKnock/Album/MainAlbumViewController.swift
  KnockKnock/KnockKnock/Assets.xcassets/frame border 2.imageset/Contents.json
  KnockKnock/KnockKnock/Assets.xcassets/frame border 2.imageset/frame border 2.svg
  KnockKnock/KnockKnock/DoorViewController.swift
  KnockKnock/KnockKnock/RoomViewController.swift
Labels: 🕸 마이즈, 🛠 refactor

#58 Animation
  KnockKnock/KnockKnock/Letter/MainLetterViewController.swift
  KnockKnock/KnockKnock/RoomViewController.swift
Labels: 💄 UI, 🐯 창브로

#62 [DESIGN] 액자 사진 레이어 추가
  KnockKnock/KnockKnock/RoomViewController.swift
Labels: 💄 UI, 🕸 마이즈

#63 [FEAT] Note animation and music update
  KnockKnock/Audio/Music/Many_Days.mp3
  KnockKnock/Audio/Music/forest.mp3
  KnockKnock/KnockKnock.xcodeproj/project.pbxproj
  KnockKnock/KnockKnock/Assets.xcassets/music1.imageset/Contents.json
  KnockKnock/KnockKnock/Assets.xcassets/music1.imageset/music1.svg
  KnockKnock/KnockKnock/Assets.xcassets/music2.imageset/Contents.json
  KnockKnock/KnockKnock/Assets.xcassets/music2.imageset/music2.svg
  KnockKnock/KnockKnock/Assets.xcassets/music3.imageset/Contents.json
  KnockKnock/KnockKnock/Assets.xcassets/music3.imageset/music3.svg
  KnockKnock/KnockKnock/RoomViewController.swift
Labels: enhancement, 💄 UI, 🤦‍♂️ 제리

#68 [FIX] 온보딩 관련 오류 수정 및 개선
  KnockKnock/KnockKnock.xcodeproj/project.pbxproj
  KnockKnock/KnockKnock/Album/MainAlbumViewController.swift
  KnockKnock/KnockKnock/Frame/MainFrameViewController.swift
  KnockKnock/KnockKnock/Letter/MainLetterViewController.swift
  KnockKnock/KnockKnock/Memo/MainMemoView.swift
  KnockKnock/KnockKnock/OnboardingView.swift
  KnockKnock/KnockKnock/OnboardingViewController.swift
  KnockKnock/KnockKnock/RoomViewController.swift
Labels: bug, 💄 UI, 💧오션

#70 [REFACTOR] 테스트 코드 삭제 및 코드 공백 제거
  KnockKnock/CoreData/CoreDataManager.swift
  KnockKnock/KnockKnock/Album/CellDetailViewController.swift
  KnockKnock/KnockKnock/Album/MainAlbumViewController.swift
  KnockKnock/KnockKnock/DoorViewController.swift
  KnockKnock/KnockKnock/Frame/FrameViewController.swift
  KnockKnock/KnockKnock/Frame/MainFrameViewController.swift
  KnockKnock/KnockKnock/Memo/MemoDetailViewController.swift
  KnockKnock/KnockKnock/OnboardingView.swift
  KnockKnock/KnockKnock/OnboardingViewController.swift
  KnockKnock/KnockKnock/RoomViewController.swift
  KnockKnock/KnockKnock/SceneDelegate.swift
Labels: 🕸 마이즈, 🛠 refactor

#71 [DESIGN] settingview UI 수정
  KnockKnock/KnockKnock/Assets.xcassets/roomImage.imageset/Contents.json
  KnockKnock/KnockKnock/Assets.xcassets/roomImage.imageset/ backimg-none3.pdf
  KnockKnock/KnockKnock/Assets.xcassets/roomImage.imageset/ backimg-none7.pdf
  KnockKnock/KnockKnock/Passcode/PasscodeViewController.swift
  KnockKnock/KnockKnock/PasscodeSetting/SettingViewController.swift
  KnockKnock/KnockKnock/PasscodeSetting/Task.swift
Labels: 💄 UI, 🐶 저니

#73 [DESIGN] BGM 버튼 이미지 사이즈 조정
  KnockKnock/KnockKnock/RoomViewController.swift
Labels: 💄 UI, 🤦‍♂️ 제리
